#!/usr/bin/env ruby
unless ARGV[0] =~ /^txmt:\/\/open\?url=/ then
    puts "You probably want this called from firefox with a txmt url."
    exit 1
end

args = ARGV[0].split("://")

file = args[2].split("&")[0]
line = args[2].split("line=")[1]
line = "1" if line == "?"

`vim --remote #{file} +#{line}`

